apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-js-test
  namespace: homepage
spec:
  selector:
    matchLabels:
      app: nest-js-test
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nest-js-test
    spec:
      containers:
        - name: nest-js-test
          image: harysetiawan23/test-api:tagVersion
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: nest-js-test
  namespace: homepage
spec:
  selector:
    app: nest-js-test
  ports:
    - port: 3030
      targetPort: 3000
  type: LoadBalancer